// fp32MultAcc.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module fp32MultAcc (
		input  wire        accumulate,  //  accumulate.accumulate,  Dynamic control signal that controls the accumulate feature.
		input  wire [31:0] fp32_mult_a, // fp32_mult_a.fp32_mult_a, Data input that supplies value to one of the FP32 multiplier operands.
		input  wire [31:0] fp32_mult_b, // fp32_mult_b.fp32_mult_b, Data input that supplies value to one of the FP32 multiplier operands.
		input  wire        clk,         //         clk.clk,         Clock port that supplies clock signals to the enabled registers according to the register parameters setting. All registers in the DSP atom are positive edge-triggered.
		input  wire [2:0]  ena,         //         ena.ena,         Clock enable signal that pairs with the clock signal and allows a clock signal to be gated.  Each register will have the same clock enable settings as the clock parameter.
		output wire [31:0] fp32_result  // fp32_result.fp32_result, The final floating point operation result of the FP DSP atom in single-precision FP32 format. The output uses unfused multiply-add rounding using round to nearest even (RNE).
	);

	fp32MultAcc_agilex_native_floating_point_dsp_100_sa6roxq agilex_native_floating_point_dsp_0 (
		.accumulate  (accumulate),  //   input,   width = 1,  accumulate.accumulate
		.fp32_mult_a (fp32_mult_a), //   input,  width = 32, fp32_mult_a.fp32_mult_a
		.fp32_mult_b (fp32_mult_b), //   input,  width = 32, fp32_mult_b.fp32_mult_b
		.clk         (clk),         //   input,   width = 1,         clk.clk
		.ena         (ena),         //   input,   width = 3,         ena.ena
		.fp32_result (fp32_result)  //  output,  width = 32, fp32_result.fp32_result
	);

endmodule
