// fp32ToFp16.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module fp32ToFp16 (
		input  wire        clk,    //    clk.clk,   All input signals must be synchronous to this clock
		input  wire        areset, // areset.reset, Active-high reset
		input  wire [0:0]  en,     //     en.en,    Allows calculation to take place when asserted
		input  wire [31:0] a,      //      a.a,     Data input
		output wire [15:0] q       //      q.q,     Data ouput
	);

	fp32ToFp16_altera_fp_functions_19110_qtmnoha fp_functions_0 (
		.clk    (clk),    //   input,   width = 1,    clk.clk
		.areset (areset), //   input,   width = 1, areset.reset
		.en     (en),     //   input,   width = 1,     en.en
		.a      (a),      //   input,  width = 32,      a.a
		.q      (q)       //  output,  width = 16,      q.q
	);

endmodule
