package common

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Paths}

/**
 * Emit SystemVerilog package from [[DdrMemoryMap]].
 *
 * Hand-written SV testbench / RTL: `import ddr_memory_map_pkg::*`
 * SpinalHDL modules: use [[DdrMemoryMap]] in Scala directly (no code gen needed).
 *
 * Default output: `common/gen/sv/ddr_memory_map_pkg.sv`
 */
object DdrMemoryMapGen extends App {

  DdrMemoryMap.sanityCheck()

  val outDir = Paths.get(sys.env.getOrElse("DDR_MAP_GEN_DIR", "common/gen/sv"))
  Files.createDirectories(outDir)

  val pkgPath = outDir.resolve("ddr_memory_map_pkg.sv")
  val pkg     = DdrMemoryMapEmit.buildSvPackage()

  Files.write(pkgPath, pkg.getBytes(StandardCharsets.UTF_8))
  println(s"Wrote $pkgPath")
}

private object DdrMemoryMapEmit {

  private def h32(v: Long): String = f"32'h$v%08X"

  private def banner(target: String): String =
    s"""// -----------------------------------------------------------------------------
// $target — AUTO-GENERATED by common.DdrMemoryMapGen
// DO NOT EDIT. Source: common/DdrMemoryMap.scala + common/doc/ddr-memory-map.md
// Regenerate: cd common && make sv
// Layout version: ${DdrMemoryMap.layoutVersion}
// -----------------------------------------------------------------------------
"""

  def buildSvPackage(): String = {
    val m = DdrMemoryMap
    s"""${banner("ddr_memory_map_pkg.sv")}
`ifndef DDR_MEMORY_MAP_PKG_SV
`define DDR_MEMORY_MAP_PKG_SV

package ddr_memory_map_pkg;

  // --- layout identity ---
  localparam logic [31:0] LAYOUT_MAGIC    = ${h32(m.layoutMagic)};
  localparam int unsigned LAYOUT_VERSION  = ${m.layoutVersion};

  // --- geometry ---
  localparam int unsigned VECTOR_DIM      = ${m.vectorDim};
  localparam int unsigned FP16_BYTES      = ${m.fp16Bytes};
  localparam logic [31:0] ROW_BYTES       = ${h32(m.rowBytes)};
  localparam int unsigned VOCAB_SIZE      = ${m.vocabSize};
  localparam int unsigned GAMMA_COUNT     = ${m.gammaCount};
  localparam int unsigned N_LAYERS        = ${m.nLayers};
  localparam int unsigned MAX_CONTEXT_LEN = ${m.maxContextLen};

  localparam int unsigned TOKEN_ID_WIDTH  = 17;
  localparam int unsigned LAYER_ID_WIDTH  = 4;
  localparam int unsigned NORM_KIND_WIDTH = 2;
  localparam int unsigned SEQ_POS_WIDTH   = 10;

  // --- region bases / sizes ---
  localparam logic [31:0] EMB_BASE              = ${h32(m.embBase)};
  localparam logic [31:0] EMB_SIZE              = ${h32(m.embSize)};
  localparam logic [31:0] EMB_END_INCLUSIVE    = ${h32(m.embEndInclusive)};

  localparam logic [31:0] RMS_GAMMA_BASE           = ${h32(m.rmsGammaBase)};
  localparam logic [31:0] RMS_GAMMA_SIZE           = ${h32(m.rmsGammaSize)};
  localparam logic [31:0] RMS_GAMMA_END_INCLUSIVE = ${h32(m.rmsGammaEndInclusive)};

  localparam logic [31:0] ATTN_BASE         = ${h32(m.attnBase)};
  localparam logic [31:0] ATTN_LAYER_STRIDE = ${h32(m.attnLayerStride)};
  localparam logic [31:0] ATTN_SIZE         = ${h32(m.attnSize)};

  localparam logic [31:0] ATTN_WQ_OFFSET = ${h32(m.attnWQOffset)};
  localparam logic [31:0] ATTN_WK_OFFSET = ${h32(m.attnWKOffset)};
  localparam logic [31:0] ATTN_WV_OFFSET = ${h32(m.attnWVOffset)};
  localparam logic [31:0] ATTN_WO_OFFSET = ${h32(m.attnWOOffset)};

  localparam logic [31:0] FFN_BASE         = ${h32(m.ffnBase)};
  localparam logic [31:0] FFN_LAYER_STRIDE = ${h32(m.ffnLayerStride)};
  localparam logic [31:0] FFN_SIZE         = ${h32(m.ffnSize)};

  localparam logic [31:0] FFN_GATE_OFFSET = ${h32(m.ffnGateOffset)};
  localparam logic [31:0] FFN_UP_OFFSET   = ${h32(m.ffnUpOffset)};
  localparam logic [31:0] FFN_DOWN_OFFSET = ${h32(m.ffnDownOffset)};

  localparam logic [31:0] KV_BASE         = ${h32(m.kvBase)};
  localparam logic [31:0] KV_LAYER_STRIDE = ${h32(m.kvLayerStride)};
  localparam logic [31:0] KV_TOKEN_STRIDE = ${h32(m.kvTokenStride)};
  localparam logic [31:0] KV_VEC_BYTES    = ${h32(m.kvVecBytes)};
  localparam logic [31:0] KV_SIZE         = ${h32(m.kvSize)};

  localparam logic [31:0] META_BASE            = ${h32(m.metaBase)};
  localparam logic [31:0] META_SIZE            = ${h32(m.metaSize)};
  localparam logic [31:0] META_GLOBAL_HDR_SIZE = ${h32(m.metaGlobalHeaderSize)};
  localparam logic [31:0] META_ATTN_SCALE_BASE = ${h32(m.metaAttnScaleBase)};
  localparam logic [31:0] META_FFN_SCALE_BASE  = ${h32(m.metaFfnScaleBase)};

  localparam logic [31:0] EXT_BASE = ${h32(m.extBase)};

  localparam logic [31:0] RMS_GAMMA_BYTES_PER_TOKEN = ${h32(m.rmsGammaBytesPerToken)};

  // --- norm kind (tuser normKind) ---
  localparam logic [1:0] NORM_KIND_NORM1      = 2'd0;
  localparam logic [1:0] NORM_KIND_NORM2      = 2'd1;
  localparam logic [1:0] NORM_KIND_FINAL_NORM = 2'd2;

  // --- address functions (byte addresses, 32-bit PL DDR window) ---

  function automatic logic [31:0] emb_row_base(input logic [16:0] token_id);
    return EMB_BASE + (32'(token_id) * ROW_BYTES);
  endfunction

  function automatic logic [5:0] gamma_index(
    input logic [3:0] layer,
    input logic [1:0] norm_kind
  );
    if (norm_kind == NORM_KIND_FINAL_NORM) begin
      return 6'(GAMMA_COUNT - 1);
    end else begin
      return (6'(layer) << 1) + 6'(norm_kind);
    end
  endfunction

  function automatic logic [31:0] gamma_addr(
    input logic [3:0] layer,
    input logic [1:0] norm_kind
  );
    return RMS_GAMMA_BASE + (32'(gamma_index(layer, norm_kind)) * ROW_BYTES);
  endfunction

  function automatic logic [31:0] attn_layer_base(input logic [3:0] layer);
    return ATTN_BASE + (32'(layer) * ATTN_LAYER_STRIDE);
  endfunction

  function automatic logic [31:0] attn_w_q(input logic [3:0] layer);
    return attn_layer_base(layer) + ATTN_WQ_OFFSET;
  endfunction

  function automatic logic [31:0] attn_w_k(input logic [3:0] layer);
    return attn_layer_base(layer) + ATTN_WK_OFFSET;
  endfunction

  function automatic logic [31:0] attn_w_v(input logic [3:0] layer);
    return attn_layer_base(layer) + ATTN_WV_OFFSET;
  endfunction

  function automatic logic [31:0] attn_w_o(input logic [3:0] layer);
    return attn_layer_base(layer) + ATTN_WO_OFFSET;
  endfunction

  function automatic logic [31:0] ffn_layer_base(input logic [3:0] layer);
    return FFN_BASE + (32'(layer) * FFN_LAYER_STRIDE);
  endfunction

  function automatic logic [31:0] ffn_gate_proj(input logic [3:0] layer);
    return ffn_layer_base(layer) + FFN_GATE_OFFSET;
  endfunction

  function automatic logic [31:0] ffn_up_proj(input logic [3:0] layer);
    return ffn_layer_base(layer) + FFN_UP_OFFSET;
  endfunction

  function automatic logic [31:0] ffn_down_proj(input logic [3:0] layer);
    return ffn_layer_base(layer) + FFN_DOWN_OFFSET;
  endfunction

  function automatic logic [31:0] kv_token_base(
    input logic [3:0] layer,
    input logic [9:0] token_pos
  );
    return KV_BASE + (32'(layer) * KV_LAYER_STRIDE) + (32'(token_pos) * KV_TOKEN_STRIDE);
  endfunction

  function automatic logic [31:0] k_addr(
    input logic [3:0] layer,
    input logic [9:0] token_pos
  );
    return kv_token_base(layer, token_pos);
  endfunction

  function automatic logic [31:0] v_addr(
    input logic [3:0] layer,
    input logic [9:0] token_pos
  );
    return kv_token_base(layer, token_pos) + KV_VEC_BYTES;
  endfunction

endpackage : ddr_memory_map_pkg

`endif // DDR_MEMORY_MAP_PKG_SV
"""
  }
}
